### ISSUE TITLE
Windows 10 Initial Setup Checklist

### ISSUE THREAD

**Issue by s7evinz** [s7evinz/public-notes#1]
- [x] Keyboard repeat.
  - ![image](https://user-images.githubusercontent.com/22605322/59161983-5b230b80-8a9e-11e9-97ed-e49e0ae9ff12.png)
- [x] Pin PowerShell to taskbar
- [x] Change `capslock` to `ctrl` using PowerShell ([details](#capslock-to-ctrl))
- [x] Install [Chocolatey](https://chocolatey.org/install)
  - PS as Admin: `Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`
- [ ] `choco install chocolateygui` (web search: https://chocolatey.org/packages)
- [ ] Install apps using `choco` see [list of packages installed](#choco-packages)
- [ ] Make Chrome default and sign in to sync.
- [ ] Bootcamp: update Apple Software
- [ ] Windows *Check for Updates*
- [ ] Sign in Outlook, setup OneDrive (require update and restart).
- [ ] iMac: Power & sleep
  - ![image](https://user-images.githubusercontent.com/22605322/59164602-fc30b700-8adc-11e9-824a-9dbe3cf4c9ad.png)

### Change capslock to ctrl<a name='capslock-to-ctrl'></a>
```ps1
# run PS as Admin
$hexified = "00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00".Split(',') | % { "0x$_"};
$kbLayout = 'HKLM:\System\CurrentControlSet\Control\Keyboard Layout';
New-ItemProperty -Path $kbLayout -Name "Scancode Map" -PropertyType Binary -Value ([byte[]]$hexified);
```

[Source](https://superuser.com/a/997448)

### Chocolatey packages installed<a name='choco-packages'></a>
For a complete list, update the packages to latest, then export the `config` file from choco GUI. Use `choco install package.config` in another machine. 

- [x] Google Chrome
- [x] Node JS
- [ ] Spoify
- [x] Steam
- [ ] Firefox
- [ ] Fiddler
- [x] Logitech Gaming Software
- [x] Logitech Options
- [ ] Origin
- [ ] iCloud
- [ ] VSCode

## Before Abandoning My Current Setup
- [ ] You've backed up Logitech Options and Gaming Software settings

**Comment by s7evinz** [comment]
- [x] Separate list and details instruction.

**Comment by s7evinz** [comment]
choco: VLC
